# -*- coding: utf-8 -*-
"""SECOUNDDAYPYTHONLEARNING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oneAzvSLENNWE5TBagwrDLOhmRvL3cjs

# SECOUND DAY OF PYTHON LEARNING


---
**LIST:**


```
LIST IS A ORDERED COLLECTION OF ELEMENTS ENCLOSED WITH SQUARE BRACKETS ([])
LIST IS CHANGABLE OR MUTABLE

```
**LIST METHODS:**


```
APPEND()-ADDS A GIVEN ELEMENT TO THE LAST OF LIST
CLEAR()- REMOVE ALL ELEMENTS FROM THE LIST
COPY()- RETURN A COPY OF GIVEN LIST
EXTEND()- ADD THE GIVEN ELEMENTS TO THE LAST OF THE LIST
COUNT()- RETURN THE NO OF ELEMENT REPEATED  IN THE GIVEN LIST
INSERT()- INSERT THE ELEMENT IN THE GIVEN INDEX
INDEX()- GIVES THE INDEX OF THE GIVEN ELEMENT IN THE LIST
POP()- REMOVES THE LAST ELEMENT IN THE LIST
REMOVE()- REMOVE THE GIVEN ELEMENT IN THE LIST OR REMOVES THE FIRST OCCURENCE OF THE ELEMENT IN THE  GIVEN LIST
REVERSE()- REVERSE THE ORDER OF THE LIST
SORT()- SORT THE GIVEN LIST
```
"""

a = [1,2,3,4] #declaration of list
print(a)
print(type(a))
#append method - just add a given element to last of list
a.append(5)
print(a)
# clear method - remove all elements in the list
a.clear()
print(a)
# copy()- return a copy of given list
b=a.copy()
print(b)
# extend() - add the elements to the last of list
a.extend([1,2,3,4])
print(a)
# count() - return the no of element repeated  in list
c= a.count(2)
print(c)
# insert()- insert a element in a given index in a list
a.insert(0,0)
print(a)
# index() - return the index of given element in a list
d=a.index(0)
print(d)
# pop() - removes the last element in a list
a.pop()
print(a)
#remove()- remove the given element in a list
a.remove(1)
print(a)
#reverse() - reverse the given list
a.reverse()
print(a)
#sort - sort the list in ascending order
a.sort()
print(a)

"""**TUPLE:**


```
TUPLE IS A ORDERED COLLECTION OF ELEMENTS ENCLOSED WITH OPEN BRACKETS (())
TUPLE CANNOT CHANGABLE

```
**TUPLE METHODS:**


```
TUPLE ARE NOT CHANGABLE ONCE CREATED SO IT HAS TWO METHODS
COUNT()- TO COUNT THE ELEMENT IN A TUPLE
INDEX() - TO KNOW THE INDEX OF FIRST REPEATED ELEMENT IN TUPLE

```





"""

a=(1,2,3,4,3,2,1)#declaration of tuple
#count() - to count the element in a tuple
b=a.count(1)
print(b)
#index() - to know the index of element in a tuple
c=a.index(2)
print(c)

"""**DICTIONARY:**


```
DICTIONARY IS THE COLLECION OF KEYS AND VALUES ENCLOSED IN A SQUARE BRACKETS({})
KEYS ARE CANNOT CHANGABLE BUT VALUES CAN CHANGABLE
KEYS AND VALUE PAIR IS CALLED AS ITEMS

```
**DICTIONARY METHODS:**


```
CLEAR()- REMOVE ALL ITEMS FROM DICTIONARY
COPY()- RETURN COPY OF A DICTIONARY
FROMKEYS() - RETURN KEY AND VALUE IF WE GIVES KEY
GET() - RETURN VALUE OF SPECIFIED KEY
ITEMS() - RETURN LIST OF TUPLE CONTAIN KEY AND VALUE
KEYS()-RETURN THE LIST OF KEYS
POPITEM() - REMOVE THE LAST ITEM FROM THE DICTIONARY
SETDEFAULT() - RETURN THE VALUE OF THE GIVEN KEY IF DONOT EXIST THEN THE KEY IS ADDED AND VALUE IS ADDED
POP()- REMOVE THE SPECIFIED KEY
VALUES() - RETURN THE LIST OF VALUES IN DICTIONARY
UPDATE() - ADD THE GIVEN ITEMS TO THE DICTIONARY
```




"""

a = {"a":1,"b":2}
#get() - return the value of specified key
b = a.get("a")
print(b)
#items() - return the list of tuple of keys and values in dictionary
c = a.items()
print(c)
#keys() - return the list of keys in dictionary
d = a.keys()
print(d)
#values() - return th list of values in dictionary
e = a.values()
print(e)
#fromkeys() - return key and value IF WE GIVE KEY
f = a.fromkeys("c")
print(f)
#update() - add the dictionary to another dictionary
a.update({"c":3})
print(a)
#popitem() - remove the last item from the dictionary
h = a.popitem()
print(h)

"""**SET:**


```
set is a unordered collection of elements no duplicates are allowed and enclosed between square brackets({})
SET IS CHANGABLE

```
**SET METHOD:**


```
add() - add element to set
clear() - remove all the elememts in a set
copy() -return a copy of set
difference() - remove same elements between a set to another set
intersection() - return same elements in two sets
isdisjoint() - return true if no common elements between two sets
pop() - remove an element from set
remove() - remove the specified element in set
union() - add the two sets
issuperset() - it return true when all elements are present in a set and is greater than the elements of the given set
issubset() - it return true when all the elements present in set and it is less then the elements of given set

```

**FROZEN SET :**


```
FROZEN SET IS DENOTED BY FROZEN METHOD
FROZEN SET CANNOT BE CHANGED

```
**FROZEN SET METHODS:**


```
copy() -return a copy of set
difference() - remove same elements between a set to another set
intersection() - return same elements in two sets
isdisjoint() - return true if no common elements between two sets
union() - add the two sets
issuperset() - it return true when all elements are present in a set and is greater than the elements of the given set
issubset() - it return true when all the elements present in set and it is less then the elements of given set
```




"""

# set
a = {1,2,3,4} #declaration of set
b ={ 3,4 , 5,6} # declaration of set
print(a)
#add() - add a element to set
a.add(5)
print(a)
#clear() - to remove all the elements from set
a.clear()
print(a)
#copy() - to copy the set to another set
a = b.copy()
print(a)
#intersection() - it return the same elements from two sets
c = a.intersection(b)
print(c)
#union() - it return add two sets
d = a.union(b)
print(d)
#issubset() - the set content all elements in another set
e = a.issubset(b)
print(e)
#issuperset() - the set content all elements in another set and greater than the another set
f = a.issuperset(b)
print(f)

#frozenset
a = frozenset([1,2,3,4]) #declaration of frozen set
print(a)
#copy() - to remove all the elements
b = a.copy()
print(b)